### ISSUE TITLE
Question: does confection offer CLI support?

### ISSUE THREAD

**Issue by vedal** [explosion/confection#15]
Hi!

I'm looking for a suitable config system for my ML project and noticed thinc and confection. I have a few criteria I'm comparing other systems with, and one source of huge boilerplate is making CLIs for the applications. 
Does confection offer automatic generation of CLI, similar to hydra or LightningCLI (jsonargparse)? It would make confection stand out, as its hard to find a system supporting both CLI and pydantic type validation, see [comment](https://github.com/pydantic/pydantic/issues/756#issuecomment-798779264)

Other than that, it seems confection scores high on most of my metrics :)

**Comment by rmitsch** [comment]
Hi @vedal! Glad `confection` caught your interest. 

Can you give me an example for what kind of CLI functionality you'd like to see? `confection` per se probably doesn't offer that, but we are currently working on extracting the [`project` functionality from spaCy](https://spacy.io/usage/projects) into its [own package](https://github.com/explosion/weasel). I could imagine that combining `confection` with `weasel` could get you closer to your goal.

**Comment by vedal** [comment]
Thank you for your swift reply @rmitsch :)
What I mean by CLI capabilities is basically automatic generation of an argparse-like parser, based on input arguments.
The most common example is probably hydra, which uses the `@hydra.main()` decorator to make each input config available on the [command line](https://hydra.cc/docs/tutorials/basic/your_first_app/simple_cli/). Its a bit involved since it has an override syntax.
A simpler example, which generates an argparse parser from a class/function by wrapping it in a `CLI` object is pytorch lightnings [LightningCLI](https://pytorch-lightning.readthedocs.io/en/1.6.2/common/lightning_cli.html), based on `CLI()` in [jsonargparse](https://jsonargparse.readthedocs.io/en/stable/#basic-usage). Here, one could apply pydantic [field types](https://pydantic-docs.helpmanual.io/usage/types/) for type checking/validation.

I think the jsonargparse-solution is more elegant than hydra.
Does it make sense? Could it be possible extend confection in a similar way?

**Comment by rmitsch** [comment]
That absolutely makes sense, and I recommend having a look at what the [`spacy projects` functionality does](https://spacy.io/usage/projects). It gives you tools to structure your (ML) project, and one of those is the [integration of `typer`](https://spacy.io/usage/projects#custom-scripts) for handling CLI arguments.

As mentioned we are currently working on moving this functionality out of spaCy and into a [separate package, `weasel`](https://github.com/explosion/weasel). I can't give you an exact date for when a first working version will be available, but it's under active development :slightly_smiling_face: 

So I think the combination of `confection` and `weasel` should cover your requirements pretty well.

**Comment by rmitsch** [comment]
@vedal, if you have further questions, feel free to reopen this.
