### ISSUE TITLE
Wrong parsing of lists of strings that are interpretable as integers

### ISSUE THREAD

**Issue by Luigi-98** [explosion/confection#29]
# Example
```python
from confection import Config

test_conf="""
[test]
a = ["001", "002"]
"""

conf = Config().from_str(test_conf)
# here conf = {'test': {'a': [1, 2]}}
```

This code interprets those strings as integers, while I'd rather have them as strings.

# Where this parsing takes place
It takes place into the __init__.py file -> Config -> _interpret_value.

It is primarily called on the string `'["001", "002"]'`. Then:
1. `result = try_load_json(value)` (result = ["001", "002"])
2. Since this result variable is a list, the function _interpret_value is recursively called on each element in the list
3. This means each string in the list is parsed as json (e.g. "001" becomes 1, because it is parsed without any quotes)

**Comment by adrianeboyd** [comment]
Thanks for the report. From the git history it looks like these lines were related to making it possible to interpolate variables within lists, but in a few quick tests I couldn't narrow exactly which cases this was added for and it looks like the test suite doesn't cover this well enough.

We'll take a closer look!
