### ISSUE TITLE
Question regarding typing 

### ISSUE THREAD

**Issue by KennethEnevoldsen** [explosion/confection#44]
Hi love the package! I have a question regarding typing within confection.

If I try to run the line:

```
registry.optimizers = catalogue.create("my_package", "optimizers")
```

I get the following error from my static type checker:
```
Cannot assign member "optimizers" for type "type[registry]"
  Member "optimizers" is unknown
```

Similarly, I also get a type error, when decorating the function:
```
@registry.optimizers.register("adam")
def create_adam():
   pass
```

```
Cannot assign member "optimizers" for type "type[registry]"
  Member "optimizers" is unknown
```

Naturally, I could just ignore the error (not ideal) alternatively I have created a wrapper class:

```
def MyRegistry(registry):
    optimizers = catalogue.create("my_package", "optimizers")
    
```

However, I am unsure if this is intended behaviour (if so it might be relevant to update the docs)

**Comment by adrianeboyd** [comment]
Thanks for the note, we'll take a look!

**Comment by rmitsch** [comment]
I don't think there's a way around this with using this syntax. Python allows dynamically adding new attributes - such as `optimizers` to `registry` - but typecheckers like `mypy` complain about it. What we're doing when adding a new attribute to `registry` is akin to
```python
class A:
    x = 3
A.y = 4
```
It makes sense that `mypy` & co don't like that.

The type-safe alternative would be to do `setattr(registry, "optimizers", catalogue.create("my_package", "optimizers"))`, but that's less concise. I'm afraid the choice is between ignoring the typechecking errors and using the more verbose `setattr()` approach. We'll add this to the readme.

**Comment by KennethEnevoldsen** [comment]
Thanks for the clarification the wrapper class seems like the best way to make it type-safe. After having worked with it for a while I would probably recommend it.

```
class Registry(registry):
    optimizers = catalogue.create("my_package", "optimizers")
```

It naturally required that don't want to dynamically extend the registry, but I don't imagine that to be common.

**Comment by rmitsch** [comment]
> It naturally required that don't want to dynamically extend the registry, but I don't imagine that to be common.

I'd agree with that, yes. Thanks again for bringing this up and proposing an alternative solution!
