### ISSUE TITLE
String values cannot contain $

### ISSUE THREAD

**Issue by MartinBernstorff** [explosion/confection#48]
Minimal example:

```python
from confection import Config

config_str = """[section]
value='^test$'
"""

Config().from_str(config_str)
```

Would love to be able to have regex strings in my config, e.g. for using [polars.exclude](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.exclude.html) to filter columns.

Raises:
```bash
InterpolationSyntaxError
'$' must be followed by '$' or '{', found: '$'
  File "C:\Users\adminmanber\Desktop\psycop-common\psycop\common\model_training_v2\config\config_utils.py", line 33, in <module>
    Config().from_str(config_str)
configparser.InterpolationSyntaxError: '$' must be followed by '$' or '{', found: '$'
```

**Comment by adrianeboyd** [comment]
Thanks for the report!

If it worked as intended, I think that `$$` should work here as the escaped form of `$` in the `configparser` format.

I haven't looked into the gory details, but it initially looks like it's being interpolated more than once, which causes problems with `$$`.

A terrible hacky workaround for this one specific problem:

```ini
[section]
value="^test$$$$"
```

The interpolated config then looks like this, where this string does still work as the intended regex:

```
[section]
value = "^test$$"
```

**Comment by MartinBernstorff** [comment]
Ah, I see, thanks! Hadn't noticed that `configparser` was part of stdlib, glad to see it!

This appears to be a bug in `configparser`, then?

**Comment by adrianeboyd** [comment]
No, we've overridden some of the interpolation with custom methods, so I think it's a bug in `confection`.

**Comment by adrianeboyd** [comment]
Ah, the problem isn't directly in the parsing/interpolation, it's in the `to_str` conversion that doesn't re-escape `$` in its own output.
