### ISSUE TITLE
Configuring pydantic classes fails with `object does not support item assignment`

### ISSUE THREAD

**Issue by ondraz** [explosion/confection#56]
Following adaptation from [readme](https://github.com/explosion/confection/blob/43c92817935610f0e0d55b7eca69357ddf07430a/README.md?plain=1#L122)  does not work when switched from `dataclass` to pydantic `BaseModel` and fails with `'MyCoolOptimizer' object does not support item assignment` in `confection/__init__.py:962`.

This is limiting Confection to be used as configuration over pydantic.

```python
import catalogue
from pydantic import BaseModel
from typing import Union, Iterable
from confection import registry, Config

registry.optimizers = catalogue.create("confection", "optimizers", entry_points=False)

class MyCoolOptimizer(BaseModel):
    learn_rate: float
    gamma: float


@registry.optimizers.register("my_cool_optimizer.v1")
def make_my_optimizer(learn_rate: Union[float, Iterable[float]], gamma: float):
    return MyCoolOptimizer(learn_rate=learn_rate, gamma=gamma)

conf_str = """
[optimizer]
@optimizers = "my_cool_optimizer.v1"
learn_rate = 0.001
gamma = 1e-8
"""

config = Config().from_str(conf_str)
resolved = registry.resolve(config)
optimizer = resolved["optimizer"]  
```

**Comment by adrianeboyd** [comment]
Thanks for the report! This looks related to similar issues reported when the config setup was still part of thinc:

- https://github.com/explosion/thinc/issues/468
- https://github.com/explosion/thinc/issues/471

**Comment by adrianeboyd** [comment]
Taking a closer look, I can't immediately replicate this error with this example.

Ah, it seems to be a difference between pydantic v1 and pydantic v2.

Can you check if pydantic v2 works for this example on your end?

**Comment by ondraz** [comment]
Thanks for the hint, upgrading to pydantic>=2 helped to resolve this issue.
