### ISSUE TITLE
Can't return pydantic BaseModels from registered function

### ISSUE THREAD

**Issue by NixBiks** [explosion/confection#57]
`registry.resolve` raises the following error

    TypeError: 'Resource' object does not support item assignment

for the given example

```python
from pydantic.main import BaseModel
import thinc

from thinc.api import Config, registry


class Resource(BaseModel):

    url: str


thinc.registry.create("resources")


@thinc.registry.resources("Resource.v1")
def make_resource(
    url: str,
) -> Resource:
    return Resource(
        url=url,
    )


config = Config().from_str(
    """
[resource]
@resources = "Resource.v1"
url = "https://thinc.ai/docs/usage-config"
"""
)
resolved = registry.resolve(config)
resource = resolved["resource"]

assert resource is not None
```

If I return `url` in `make_resource` (add use `str` for return type instead) then it works just fine. Is it on purpose that pydantic can't be returned in registered functions?

**Comment by adrianeboyd** [comment]
Taking another look at this following #56, it looks like this is supported in pydantic v2.

**Comment by adrianeboyd** [comment]
I will tentatively close this issue since it seems to be supported in pydantic v2, but feel free to reopen if you're still running into problems!
